
/*  Members types actions  */

export const ADD_MEMBER_ERROR = 'ADD_MEMBER_ERROR';
export const ADD_MEMBER_LOADING = 'ADD_MEMBER_LOADING';
export const ADD_MEMBER_SUCCESS = 'ADD_MEMBER_SUCCESS';

export const UPDATE_MEMBER_ERROR = 'UPDATE_MEMBER_ERROR';
export const UPDATE_MEMBER_LOADING = 'UPDATE_MEMBER_LOADING';
export const UPDATE_MEMBER_SUCCESS = 'UPDATE_MEMBER_SUCCESS';


export const FETCH_MEMBER_ERROR = 'FETCH_MEMBER_ERROR';
export const FETCH_MEMBER_LOADING = 'FETCH_MEMBER_LOADING';
export const FETCH_MEMBER_SUCCESS = 'FETCH_MEMBER_SUCCESS';


export const FETCH_BY_ID_MEMBER_ERROR = 'FETCH_BY_ID_MEMBER_ERROR';
export const FETCH_BY_ID_MEMBER_LOADING = 'FETCH_BY_ID_MEMBER_LOADING';
export const FETCH_BY_ID_MEMBER_SUCCESS = 'FETCH_BY_ID_MEMBER_SUCCESS';

export const DELETE_MEMBER_ERROR = 'DELETE_MEMBER_ERROR';
export const DELETE_MEMBER_LOADING = 'DELETE_MEMBER_LOADING';
export const DELETE_MEMBER_SUCCESS = 'DELETE_MEMBER_SUCCESS';


/*  Rubriques types actions  */

export const ADD_RUBRIQUE_ERROR = 'ADD_RUBRIQUE_ERROR';
export const ADD_RUBRIQUE_LOADING = 'ADD_RUBRIQUE_LOADING';
export const ADD_RUBRIQUE_SUCCESS = 'ADD_RUBRIQUE_SUCCESS';

export const UPDATE_RUBRIQUE_ERROR = 'UPDATE_RUBRIQUE_ERROR';
export const UPDATE_RUBRIQUE_LOADING = 'UPDATE_RUBRIQUE_LOADING';
export const UPDATE_RUBRIQUE_SUCCESS = 'UPDATE_RUBRIQUE_SUCCESS';


export const FETCH_RUBRIQUE_ERROR = 'FETCH_MEMBER_ERROR';
export const FETCH_RUBRIQUE_LOADING = 'FETCH_MEMBER_LOADING';
export const FETCH_RUBRIQUE_SUCCESS = 'FETCH_MEMBER_SUCCESS';


export const DELETE_RUBRIQUE_ERROR = 'DELETE_RUBRIQUE_ERROR';
export const DELETE_RUBRIQUE_LOADING = 'DELETE_RUBRIQUE_LOADING';
export const DELETE_RUBRIQUE_SUCCESS = 'DELETE_RUBRIQUE_SUCCESS';